[build-system]
requires = [
    "pip<=23.0",
    "setuptools>=62,<=65",
    "wheel",
    "ninja",
    "cmake>=3.22",
    "numpy"
]
build-backend = "setuptools.build_meta"

[project]
name = "mymodule"
version = "0.0.1"
requires-python = ">=3.8"

dependencies = [
    "numpy"
]
